export const fretsFretboard = {
  Fret1: {
    string1: "hide",
    string2: "hide",
    string3: "hide",
    string4: "hide",
    string5: "hide",
    string6: "hide",
  },
  Fret2: {
    string1: "hide",
    string2: "hide",
    string3: "hide",
    string4: "hide",
    string5: "hide",
    string6: "hide",
  },
  Fret3: {
    string1: "hide",
    string2: "hide",
    string3: "hide",
    string4: "hide",
    string5: "hide",
    string6: "hide",
  },
  Fret4: {
    string1: "hide",
    string2: "hide",
    string3: "hide",
    string4: "hide",
    string5: "hide",
    string6: "hide",
  },
  Fret5: {
    string1: "hide",
    string2: "hide",
    string3: "hide",
    string4: "hide",
    string5: "hide",
    string6: "hide",
  },
  Fret6: {
    string1: "hide",
    string2: "hide",
    string3: "hide",
    string4: "hide",
    string5: "hide",
    string6: "hide",
  },
  Fret7: {
    string1: "hide",
    string2: "hide",
    string3: "hide",
    string4: "hide",
    string5: "hide",
    string6: "hide",
  },
  Fret8: {
    string1: "hide",
    string2: "hide",
    string3: "hide",
    string4: "hide",
    string5: "hide",
    string6: "hide",
  },
  Fret9: {
    string1: "hide",
    string2: "hide",
    string3: "hide",
    string4: "hide",
    string5: "hide",
    string6: "hide",
  },
  Fret10: {
    string1: "hide",
    string2: "hide",
    string3: "hide",
    string4: "hide",
    string5: "hide",
    string6: "hide",
  },
  Fret11: {
    string1: "hide",
    string2: "hide",
    string3: "hide",
    string4: "hide",
    string5: "hide",
    string6: "hide",
  },
  Fret12: {
    string1: "hide",
    string2: "hide",
    string3: "hide",
    string4: "hide",
    string5: "hide",
    string6: "hide",
  },
  Fret13: {
    string1: "hide",
    string2: "hide",
    string3: "hide",
    string4: "hide",
    string5: "hide",
    string6: "hide",
  },
  Fret14: {
    string1: "hide",
    string2: "hide",
    string3: "hide",
    string4: "hide",
    string5: "hide",
    string6: "hide",
  },
  Fret15: {
    string1: "hide",
    string2: "hide",
    string3: "hide",
    string4: "hide",
    string5: "hide",
    string6: "hide",
  },
  Fret16: {
    string1: "hide",
    string2: "hide",
    string3: "hide",
    string4: "hide",
    string5: "hide",
    string6: "hide",
  },
  Fret17: {
    string1: "hide",
    string2: "hide",
    string3: "hide",
    string4: "hide",
    string5: "hide",
    string6: "hide",
  },
};

export const fretsChordBox = {
  chordFret1: {
    chordString1: 0,
    chordString2: 0,
    chordString3: 0,
    chordString4: 0,
    chordString5: 0,
    chordString6: 0,
  },
  chordFret2: {
    chordString1: 0,
    chordString2: 0,
    chordString3: 0,
    chordString4: 0,
    chordString5: 0,
    chordString6: 0,
  },
  chordFret3: {
    chordString1: 0,
    chordString2: 0,
    chordString3: 0,
    chordString4: 0,
    chordString5: 0,
    chordString6: 0,
  },
  chordFret4: {
    chordString1: 0,
    chordString2: 0,
    chordString3: 0,
    chordString4: 0,
    chordString5: 0,
    chordString6: 0,
  },
  chordFret5: {
    chordString1: 0,
    chordString2: 0,
    chordString3: 0,
    chordString4: 0,
    chordString5: 0,
    chordString6: 0,
  },
};
